kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22