kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 5050