apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-deployment
  labels:
    app: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp
        imagePullPolicy: Never
        ports:
        - containerPort: 21