apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 31110
        - containerPort: 31111
        livenessProbe:
          exec:
            command:
            - sh
            - /launch-crashed-services.sh
          initialDelaySeconds: 25
          periodSeconds: 20
       