kind: Service
apiVersion: v1
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 21
    targetPort: 21
  - name: p1
    port: 21100
    targetPort: 21100
  - name: p2
    port: 21101
    targetPort: 21101